# Programming Assignment_07

Q 1. Write a Python Program to find sum of array

In [1]:
import numpy as np

In [54]:
#Ans:-
def sum_array():
    a = [1,2,3,4,5,6,7,8]
    arr = np.array(a)
    return arr.sum()
sum_array()

36

Q 2. Write a Python Program to find largest element in an array?

In [55]:
#Ans:-
def largest_array():
    b = [4,6,8,2,9,3,4,5,1]
    arr1 = np.array(b)
    max2 = arr1[0]
    for i in arr1:
        if i > max2:
            max2 = i
    return max2
largest_array()


9

Q 3. Write a Python Program for array rotation ?

In [56]:
#Ans:-
arr1

array([4, 6, 8, 2, 9, 3, 4, 5, 1])

In [57]:
arr1[::-1]

array([1, 5, 4, 3, 9, 2, 8, 6, 4])

Q 4. Write a Python Program to Split the array and add the first part to the end ?

In [58]:
#Ans:-
arr2 = np.array([2,5,7,8,3,4,5,9,1])
arr2

array([2, 5, 7, 8, 3, 4, 5, 9, 1])

In [59]:
add_last_first = arr2[0]+arr2[-1]
print("add the first and last part {} & {} is :".format(arr2[0],arr2[-1]),add_last_first)

add the first and last part 2 & 1 is : 3


Q 5. Write a Python Program to check if given array is Monotonic ?

In [67]:
#Ans:-
def monotonic(a):
    global n
    n = len(a)
    if n ==1:
        print(True)
    else:
        if all(a[i] <= a[i+1] for i in range(0,n-1) or a[i] >= a[i+1]for i in range(0,n-1)):
            print("true")
        else:
            print("flase")
monotonic([1,3,6]) 
monotonic([5,4,8])

true
flase
