# Programming Assignment_08

Q 1. Write a Python Program to Add two Matrices ?

In [47]:
#Ans:-
import numpy as np
arr = np.linspace(1,20,num=9)
arr1 = arr.reshape(3,3)
arr1

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [46]:
arr2 = arr1+1
arr2

array([[ 2.   ,  4.375,  6.75 ],
       [ 9.125, 11.5  , 13.875],
       [16.25 , 18.625, 21.   ]])

In [13]:
arr1 + arr2

array([[ 3.  ,  7.75, 12.5 ],
       [17.25, 22.  , 26.75],
       [31.5 , 36.25, 41.  ]])

Q 2. Write a Python Program to Multiply two Matrices ?

In [14]:
#Ans:-
arr1 * arr2

array([[  2.      ,  14.765625,  38.8125  ],
       [ 74.140625, 120.75    , 178.640625],
       [247.8125  , 328.265625, 420.      ]])

Q 3. Write a Python Program to transpose a Matrix ?

In [16]:
#Ans:-
arr3 = np.linspace(1,30,num=12)
arr3.reshape(4,3)

array([[ 1.        ,  3.63636364,  6.27272727],
       [ 8.90909091, 11.54545455, 14.18181818],
       [16.81818182, 19.45454545, 22.09090909],
       [24.72727273, 27.36363636, 30.        ]])

In [17]:
arr3.reshape(6,2)

array([[ 1.        ,  3.63636364],
       [ 6.27272727,  8.90909091],
       [11.54545455, 14.18181818],
       [16.81818182, 19.45454545],
       [22.09090909, 24.72727273],
       [27.36363636, 30.        ]])

Q 4. Write a Python Program to sort Words in an Alphabatical Order ?

In [45]:
#Ans:-
string = "hellow well come to my worlled let see who is go to participate good to go "
string1 =string.split()
string1.sort()
string1

['come',
 'go',
 'go',
 'good',
 'hellow',
 'is',
 'let',
 'my',
 'participate',
 'see',
 'to',
 'to',
 'to',
 'well',
 'who',
 'worlled']

Q 5. Write a Python Program to remove Punctuations From a String ?

In [38]:
#Ans:-
str1 = input("enter the str :")
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
for i in str1:
    if i not in punctuations:
        print(i,end= "")

enter the str :wellcome to#$my @#$%the gol
wellcome tomy the gol